### ISSUE TITLE
XP Economy Provider - Price doesn't change

### ISSUE THREAD

**Issue by n00bslayr94** [DuoIncure/ComplexUpgradeUI#15]
https://github.com/ComplexityEU/ComplexUpgradeUI/assets/132199379/1d5fcc27-f348-4700-8ae9-947e025a293e

I've set the config file to use XP, however the pricing doesn't update in-game for XP - it always uses "5".

See below - mending enchant is set to 45, but the video attached shows it costs 5.

```
# Economy Options
economy:
  # Economy provider to use. Supported options:  "economyapi", "bedrockeconomy" and "xp"
  provider: xp

#List of enchants and their configurable values
#PLEASE NOTE. SOME ENCHANTS ARE NOT ADDED BY POCKETMINE-MP AND AS A RESULT ARE NOT IN THIS PLUGIN.
enchants:
  #The tool for the enchants
  pickaxe:
    #Enchant name
    efficiency:
      #Max level for enchant
      max-level: 1
      # Cost per enchant level. If money is chosen 1 = $1. If XP is chosen 1 = 1 XP level.
      cost: 5
    #Enchant name
    unbreaking:
      #Max level for enchant
      max-level: 1
      # Cost per enchant level. If money is chosen 1 = $1. If XP is chosen 1 = 1 XP level.
      cost: 5
    #Enchant name
    silk_touch:
      #Max level for enchant
      max-level: 1
      # Cost per enchant level. If money is chosen 1 = $1. If XP is chosen 1 = 1 XP level.
      cost: 5
    mending:
      max-level: 1
      cost: 45 
```
